name: Python Check

on:
  push:
  pull_request:

jobs:
  pycompile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: python -m py_compile src/indexer/app.py src/public_api/app.py src/admin_api/app.py
